# Generated by Django 3.2.8 on 2021-11-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money',
        ),
    ]
