# Generated by Django 3.2.8 on 2021-11-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('loot', '0002_delete_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokeball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('level', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'pokeball',
            },
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'potions',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='PotionInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('potion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot.potion')),
            ],
            options={
                'verbose_name': "Potion's Inventory",
                'verbose_name_plural': "Potion's Inventory",
                'db_table': 'potions_inventory',
            },
        ),
        migrations.CreateModel(
            name='PokeballInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('pokeball', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot.potion')),
            ],
            options={
                'verbose_name': "Pokeball's Inventory",
                'verbose_name_plural': "Pokeball's Inventory",
                'db_table': 'pokeballs_inventory',
            },
        ),
    ]
