# Generated by Django 3.2.8 on 2021-11-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0003_pokeball_pokeballinventory_potion_potioninventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeballinventory',
            name='pokeball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loot.pokeball'),
        ),
    ]
