# Generated by Django 3.2.8 on 2021-11-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('loot', '0004_alter_pokeballinventory_pokeball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeballinventory',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokeballs', to='inventory.inventory'),
        ),
        migrations.AlterField(
            model_name='pokeballinventory',
            name='pokeball',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokeball', to='loot.pokeball'),
        ),
    ]
