global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: web
    metrics_path: /prometheus/metrics/
    static_configs:
      - targets: ['yourhost:8765']
